name: Build Dockerfiles Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    permissions:
      security-events: write
      contents: read

    steps:
    #- uses: actions/checkout@v4
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Build the Docker image
     # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: |
          sudo mkdir -p /etc/systemd/system/docker.service.d
          sudo systemctl daemon-reload
          sudo systemctl restart docker
          cd ./ivsr_ffmpeg_plugin
          ./build_docker.sh --ov_version 2024.5s --os_version rockylinux9
